### ISSUE TITLE
搜索关键词的匹配结果会考虑优化下显示效果吗？

### ISSUE THREAD

**Issue by tyf2018** [guopenghui/obsidian-quiet-outline#10]
如题，搜索关键词的匹配结果，会考虑优化下显示效果吗？比如增加高亮显示，类似下图所示（目前的下划线效果，感觉不太醒目，不易分辨）： 

![image](https://user-images.githubusercontent.com/56342788/161035494-725d48e8-e5c6-48d3-988d-8929141abd54.png)

**Comment by guopenghui** [comment]
是指只高亮搜索的那部分吗，这个可能有些难度。因为标题支持markdown渲染，说不定实际的内容是一个很复杂的字符串，从中找到渲染后的对应内容比较麻烦。

现在的搜索是用原始标题字符串来进行的，比如你写一个`# <font color="red">html</font>`，大纲里面只会显示红色的`html`，但是在搜索栏搜`font`也是会命中的。

如果是觉得现在的下划线不太明显，可以看看修改那条线的宽度或颜色，应该是`n-tree-node-content__text`的`border-bottom`

**Comment by tyf2018** [comment]
> 应该是 `n-tree-node-content__text`的 `border-bottom`

这个参数会把所有内容都加上下划线。我只想高亮匹配结果所在行。另外在亮色模式下，这条下划线会直接消失，应该是被主题的背景色覆盖了

**Comment by guopenghui** [comment]
可以这么设置
```css
.theme-dark .n-tree .n-tree-node.n-tree-node--highlight .n-tree-node-content .n-tree-node-content__text {
  border-bottom-color: red;
}
.theme-light .n-tree .n-tree-node.n-tree-node--highlight .n-tree-node-content .n-tree-node-content__text {
  border-bottom-color: blue;
}
```
