### ISSUE TITLE
能否在outline中参照当前主题设置，给标题文本也进行着色

### ISSUE THREAD

**Issue by bushnerd** [guopenghui/obsidian-quiet-outline#105]
在outline里已经有了竖线是根据主题设置进行着色的，能否增加选项，给标题文本进行着色，这样标题和标题之间会更醒目一些。
![image](https://user-images.githubusercontent.com/28666253/224867828-e8d5f4f4-2fc0-4827-8d05-f5ab61e2a46b.png)

**Comment by yett1873** [comment]
赞同，希望能像图左floating toc插件一样设置每级heading的颜色，层级关系会醒目很多！

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/75569851/ecb050bf-f564-4cfa-ad53-79e2527bb028)

**Comment by bushnerd** [comment]
我按照这个设置成了Minimal的标题的样式，供大家参考。
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/28666253/1071f312-65f2-4769-b803-aab358f52ba0)

```css
.n-tree-node.level-1 .n-tree-node-content {
    color: #d9707d;
}

.n-tree-node.level-2 .n-tree-node-content {
    color: #c99b6e;
}

.n-tree-node.level-3 .n-tree-node-content {
    color: #c7c16f;
}

.n-tree-node.level-4 .n-tree-node-content {
    color: #8cb87a;
}

.n-tree-node.level-5 .n-tree-node-content {
    color: #63b1f0;
}

.n-tree-node.level-6 .n-tree-node-content {
    color: #a470c2;
}
```
