### ISSUE TITLE
Option to add colors for headers from theme

### ISSUE THREAD

**Issue by d9k** [guopenghui/obsidian-quiet-outline#141]
| before | after|
|-----------|---------|
| ![Selection_2023-11-22_21-56-18](https://github.com/guopenghui/obsidian-quiet-outline/assets/7331988/7c9b012e-a27a-412e-b2ac-53e55ee4475a) | ![Selection_2023-11-22_21-55-56](https://github.com/guopenghui/obsidian-quiet-outline/assets/7331988/eeb8abd6-b0fe-4f48-9692-3f3f2b7fc684)
 |

Also selected header font weight must not differ from font weight of non-selected items.
Because different font weight of selected item forces quiet outline tree markup to "jump" back and forth on scrolling: 1-line item sometimes becomes 2-lines item on different font weight

**Comment by d9k** [comment]
My `quiet-outline-plugin-mod.css` snippet (can be added in Obisidan options -> Appearance -> CSS snippets)

```css
/** Headers color */

.quiet-outline .n-tree .n-tree-node.level-1 > .n-tree-node-content .n-tree-node-content__text,
.quiet-outline .n-tree .n-tree-node.level-1 > .n-tree-node-content .n-tree-node-content__text a.tag {
  color: var(--h1-color);
}

.quiet-outline .n-tree .n-tree-node.level-2 > .n-tree-node-content .n-tree-node-content__text,
.quiet-outline .n-tree .n-tree-node.level-2 > .n-tree-node-content .n-tree-node-content__text a.tag{
  color: var(--h2-color);
}

.quiet-outline .n-tree .n-tree-node.level-3 > .n-tree-node-content .n-tree-node-content__text,
.quiet-outline .n-tree .n-tree-node.level-3 > .n-tree-node-content .n-tree-node-content__text a.tag{
  color: var(--h3-color);
}

.quiet-outline .n-tree .n-tree-node.level-4 > .n-tree-node-content .n-tree-node-content__text,
.quiet-outline .n-tree .n-tree-node.level-4 > .n-tree-node-content .n-tree-node-content__text a.tag{
  color: var(--h4-color);
}

.quiet-outline .n-tree .n-tree-node.level-5 > .n-tree-node-content .n-tree-node-content__text,
.quiet-outline .n-tree .n-tree-node.level-5 > .n-tree-node-content .n-tree-node-content__text a.tag{
  color: var(--h5-color);
}


/** Selected node */
.quiet-outline .n-tree-node.located {
  background-color: #16332d;
}

.quiet-outline .n-tree-node.located p {
  font-weight: 400;
}

.quiet-outline .n-tree-node.located p {
  color: unset;
}

```
