### ISSUE TITLE
无法调节h2-h6的字体大小

### ISSUE THREAD

**Issue by yett1873** [guopenghui/obsidian-quiet-outline#143]
如图，使用css片段如下，可以调节level1的字体大小，但无法调节其余层级的字体大小。在一个空的库里实验，排除其它插件和css的影响后依然如此，故请求帮助。

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/75569851/a418b6d1-3623-4666-9112-8c88c08c9f10)

```css
.n-tree-node.level-1 .n-tree-node-content {
    color: #B4637A;
    font-size: 2rem;
}
.n-tree-node.level-2 .n-tree-node-content {
    color: #D59C89;
    font-size: 1.5rem;
}
.n-tree-node.level-3 .n-tree-node-content {
    color: #E3A62D;
    font-size: 1.5rem;
}
.n-tree-node.level-4 .n-tree-node-content {
    color: #92BB70;
    font-size: 1.5rem;
}
.n-tree-node.level-5 .n-tree-node-content {
    color: #328EB3;
    font-size: 1.1rem;
}
.n-tree-node.level-6 .n-tree-node-content {
    color: #B26DA6;
    font-size: 1.1rem;
}
```
