### ISSUE TITLE
彩虹大纲线不生效问题

### ISSUE THREAD

**Issue by aiqyqy** [guopenghui/obsidian-quiet-outline#195]
你好，我的彩虹大纲线不生效啊，将插件升级为最新版本，卸载重装均无法解决，obsidian版本是v1.7.5。

![image](https://github.com/user-attachments/assets/797861c3-d586-4aa6-9a53-f9f997ba3888)

这是演示文档中的，能看到有彩虹大纲线
![image](https://github.com/user-attachments/assets/cd2dcfba-5f54-48fd-a278-2f2d7970f1be)

还有设置“主颜色 明/暗“ 是啥意思，我看这个配置并没有在大纲中生效啊。

**Comment by guopenghui** [comment]
用的blue topaz主题吧。 bt主题给这个插件特殊做了适配，可以在style setting插件里面关掉，就有彩虹线了。要不就是换个主题，就能看到了。

主题色就是这个部分的颜色：
![image](https://github.com/user-attachments/assets/85b320d4-a221-4806-a815-2329c608314e)

**Comment by aiqyqy** [comment]
@已经解决了，感谢，还有咱这个主题能给一份吗
![image](https://github.com/user-attachments/assets/f283f2b0-6fa3-439f-b3e4-5b19411383bd)

**Comment by guopenghui** [comment]
> @已经解决了，感谢，还有咱这个主题能给一份吗
> ![image](https://github.com/user-attachments/assets/f283f2b0-6fa3-439f-b3e4-5b19411383bd)
> 

这个就是以前的 blue topaz主题，两年多以前的了，当时obsidian还是0.几版本，现在已经不能用了

**Comment by aiqyqy** [comment]
> > @已经解决了，感谢，还有咱这个主题能给一份吗
> > ![image](https://private-user-images.githubusercontent.com/55039821/385844958-f283f2b0-6fa3-439f-b3e4-5b19411383bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDkxNTIsIm5iZiI6MTczMjEwODg1MiwicGF0aCI6Ii81NTAzOTgyMS8zODU4NDQ5NTgtZjI4M2YyYjAtNmZhMy00MzlmLWIzZTQtNWIxOTQxMTM4M2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEzMjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmNhOWEyOTAyMzJmZjg5MmU3YmYyYWZkM2ZjMjZlOGU1ZjAyZDkyOGI4MjExZjExYjZjNDEyYWUyZTNkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8oAnj-IdtgmRNlqykQxHajMz3YizFw7oN6DU180pAC0)
> 
> 这个就是以前的 blue topaz主题，两年多以前的了，当时obsidian还是0.几版本，现在已经不能用了

我主要觉得那个蓝色的箭头挺醒目的，使整个大纲更清晰明了，这个有办法实现吗。

**Comment by guopenghui** [comment]
实现应该类似：
```css
.workspace-leaf .search-result-container.mod-global-search .tree-item-self.search-result-file-title.is-clickable .collapse-icon::before {
  content: "↓";
  font-size: 14px;
  margin-left: 0px;
  font-weight: bold;
  font-family: 'Inter';
  color: var(--text-accent);
  transition: transform 10ms linear 0s;
}
```

翻一翻项目的css文件里可以找到
https://github.com/PKM-er/Blue-Topaz_Obsidian-css/blob/v5.2/obsidian.css
