### ISSUE TITLE
鼠标处大纲和quiet-outline窗口处点击大纲 能不能分别高亮？有没有好用的css

### ISSUE THREAD

**Issue by oushiei120** [guopenghui/obsidian-quiet-outline#241]
```css

/* 当前选中的标题 - 多种可能的选择器 */
.quiet-outline .n-tree-node-content.is-active,
.quiet-outline .n-tree-node-content.selected,
.quiet-outline .n-tree-node-content[aria-selected="true"],
.quiet-outline .n-tree-node-content.n-tree-node-content--selected,
.quiet-outline .n-tree-node.n-tree-node--selected .n-tree-node-content {
    background-color: #ff4757 !important;
    border-left: 5px solid #ff3742 !important;
    padding-left: 8px !important;
    margin-left: -3px !important;
    border-radius: 3px !important;
    box-shadow: 2px 2px 8px rgba(255, 71, 87, 0.4) !important;
}

/* 选中状态下的文字也要特别处理 */
.quiet-outline .n-tree-node-content.is-active .n-tree-node-content__text p,
.quiet-outline .n-tree-node-content.selected .n-tree-node-content__text p,
.quiet-outline .n-tree-node-content[aria-selected="true"] .n-tree-node-content__text p,
.quiet-outline .n-tree-node-content.n-tree-node-content--selected .n-tree-node-content__text p,
.quiet-outline .n-tree-node.n-tree-node--selected .n-tree-node-content .n-tree-node-content__text p {
    color: #ffffff !important;
    font-weight: 800 !important;
    text-shadow: 1px 1px 2px rgba(0,0,0,0.3) !important;
}

/* 鼠标悬停效果 */
.quiet-outline .n-tree-node-content:hover {
    background-color: rgba(255, 255, 255, 0.1) !important;
}


```

好像不太行 ，我想分别高亮 【鼠标点击位置所属大纲】 【quiet-outline 窗口点击大纲】这两个
