### ISSUE TITLE
建议固定搜索框

### ISSUE THREAD

**Issue by exam-ple** [guopenghui/obsidian-quiet-outline#31]
现在下滑时搜索框也会跟着滑走, 要搜索内容时, 得重新滑到顶部才能输入内容, 希望搜索框能固定着, 不管目录下滑到哪个标题都能看到搜索框, 这样想搜索随时就可以搜索

感谢开发这么好用的插件, 里面的一些功能英文论坛里有些人都提了好几年了, 希望更多人能知道这个插件的存在

**Comment by guopenghui** [comment]
后面更新的时候考虑搞个设置选项。
现在暂时可以在`styles.css`里面加上这几句，能实现相同的功能：
```css
/* 固定功能栏 */
.quiet-outline {
  height: 100%;
}
.quiet-outline #container {
  height: 100%;
}
.quiet-outline .n-config-provider {
  display:flex;
  flex-direction:column;
  height: 100%;
}
.quiet-outline .n-tree {
  overflow: auto;
}
```
