### ISSUE TITLE
[Problem] Quiet Outline面板置放在下方時，最後的標題會被狀態欄蓋住

### ISSUE THREAD

**Issue by emisjerry** [guopenghui/obsidian-quiet-outline#72]
如下圖，有22, 23標題，但只顯示到21，似乎被狀態欄遮住了?

![image](https://user-images.githubusercontent.com/131511/201313806-d1e7b709-7002-444b-a0f9-8adcd7a98828.png)

**Comment by guopenghui** [comment]
可以先自己加一个css规则来解决：
```css
.quiet-outline {
    padding-bottom: 24px;
}
```
