### ISSUE TITLE
Link color uses wrong CSS selector

### ISSUE THREAD

**Issue by NomarCub** [guopenghui/obsidian-quiet-outline#82]
I have the following CSS snippet:

```css
body {
  --link-external-color: #66b1fa;
}
```

It should only make external links blue, but it makes the internal links in the outline blue too.
![image](https://user-images.githubusercontent.com/5298006/209480591-a4d8a916-04c4-473f-978a-a1e8f2ca950d.png)
